import type { DecorationScene } from './types'

export const decorationPresets = {
  marketingFlow: {
    id: 'marketing-flow',
    name: 'Marketing / Flow / Connected Sections',
    figma: 'Marketing / Page / Shared Decoration Flow',
    layers: [
      {
        type: 'dot-field',
        id: 'dots-patch-upper-left',
        figma: 'Decoration / Dot Patch / Upper Left',
        region: {
          position: { x: '0', y: '6rem', anchor: 'top-left' },
          size: { w: '48%', h: '30%' },
        },
        dotPattern: {
          variant: 'grid',
          color: 'neutral',
          size: 3,
          gap: 22,
          opacity: 0.15,
          fade: 'right',
        },
      },
      {
        type: 'dot-field',
        id: 'dots-patch-mid-right',
        figma: 'Decoration / Dot Patch / Mid Right',
        region: {
          position: { x: '0', y: '40%', anchor: 'top-right' },
          size: { w: '42%', h: '24%' },
        },
        dotPattern: {
          variant: 'grid',
          color: 'neutral',
          size: 3,
          gap: 24,
          opacity: 0.12,
          fade: 'left',
        },
      },
      {
        type: 'dot-field',
        id: 'dots-patch-center',
        figma: 'Decoration / Dot Patch / Center River',
        region: {
          position: { x: '50%', y: '56%', anchor: 'center' },
          size: { w: '68%', h: '20%' },
        },
        dotPattern: {
          variant: 'grid',
          color: 'neutral',
          size: 3,
          gap: 20,
          opacity: 0.1,
          fade: 'radial',
        },
      },
      {
        type: 'dot-field',
        id: 'dots-patch-lower-left',
        figma: 'Decoration / Dot Patch / Lower Left',
        region: {
          position: { x: '0', y: '72%', anchor: 'top-left' },
          size: { w: '40%', h: '26%' },
        },
        dotPattern: {
          variant: 'grid',
          color: 'neutral',
          size: 3,
          gap: 26,
          opacity: 0.11,
          fade: 'radial-tl',
        },
      },
      {
        type: 'dot-field',
        id: 'dots-patch-lower-brand',
        figma: 'Decoration / Dot Patch / Lower Brand',
        region: {
          position: { x: '0', y: '82%', anchor: 'top-right' },
          size: { w: '46%', h: '22%' },
        },
        dotPattern: {
          variant: 'gradient-grid',
          color: 'brand',
          size: 3,
          gap: 22,
          opacity: 0.09,
          gradient: 'brand',
          fade: 'diagonal',
        },
      },
      {
        type: 'gradient-blob',
        id: 'flow-blob-top-left',
        figma: 'Decoration / Flow Blob / Top Left',
        color: 'accent-5',
        colorMix: 64,
        colorStop: 64,
        size: { w: '46rem', h: '46rem' },
        position: { x: '-12rem', y: '8rem', anchor: 'top-left' },
        blur: 'md',
        opacity: 0.44,
        motion: { preset: 'drift-a' },
      },
      {
        type: 'gradient-blob',
        id: 'flow-blob-upper-right',
        figma: 'Decoration / Flow Blob / Upper Right',
        color: 'button-primary-gradient-start',
        colorMix: 56,
        colorStop: 66,
        size: { w: '42rem', h: '42rem' },
        position: { x: '-12rem', y: '22rem', anchor: 'top-right' },
        blur: 'sm',
        opacity: 0.4,
        motion: { preset: 'drift-b' },
      },
      {
        type: 'gradient-blob',
        id: 'flow-blob-mid-left',
        figma: 'Decoration / Flow Blob / Mid Left',
        color: 'accent-20',
        colorMix: 60,
        colorStop: 66,
        size: { w: '40rem', h: '40rem' },
        position: { x: '-13rem', y: '50%', anchor: 'top-left' },
        blur: 'sm',
        opacity: 0.36,
        motion: { preset: 'drift-c' },
      },
      {
        type: 'gradient-blob',
        id: 'flow-blob-center-upper',
        figma: 'Decoration / Flow Blob / Center Upper',
        color: 'accent-5',
        colorMix: 38,
        colorStop: 72,
        size: { w: '56rem', h: '28rem' },
        position: { x: '50%', y: '36%', anchor: 'center' },
        blur: 'md',
        opacity: 0.3,
        motion: { preset: 'drift-b' },
      },
      {
        type: 'gradient-blob',
        id: 'flow-blob-center-lower',
        figma: 'Decoration / Flow Blob / Center Lower',
        color: 'button-primary-gradient-start',
        colorMix: 34,
        colorStop: 74,
        size: { w: '54rem', h: '26rem' },
        position: { x: '50%', y: '64%', anchor: 'center' },
        blur: 'md',
        opacity: 0.24,
        motion: { preset: 'drift-c' },
      },
      {
        type: 'gradient-blob',
        id: 'flow-blob-lower-right',
        figma: 'Decoration / Flow Blob / Lower Right',
        color: 'accent-14',
        colorMix: 54,
        colorStop: 66,
        size: { w: '44rem', h: '44rem' },
        position: { x: '-14rem', y: '74%', anchor: 'top-right' },
        blur: 'md',
        opacity: 0.42,
        motion: { preset: 'drift-a' },
      },
      {
        type: 'gradient-blob',
        id: 'flow-blob-lower-left',
        figma: 'Decoration / Flow Blob / Lower Left',
        color: 'accent-5',
        colorMix: 52,
        colorStop: 68,
        size: { w: '36rem', h: '36rem' },
        position: { x: '-10rem', y: '84%', anchor: 'top-left' },
        blur: 'sm',
        opacity: 0.3,
        motion: { preset: 'drift-b' },
      },
    ],
  },

  howItWorks: {
    id: 'how-it-works',
    name: 'How It Works / Light / Dot Grid',
    figma: 'Marketing / Sections / How It Works / Background',
    layers: [
      {
        type: 'dot-field',
        id: 'dot-grid',
        figma: 'Decoration / Dot Grid / 18',
        dotPattern: {
          variant: 'grid',
          color: 'neutral',
          size: 3,
          gap: 18,
          opacity: 0.18,
          fade: 'right',
        },
      },
    ],
  },

  scriptSection: {
    id: 'create-script',
    name: 'Create Script / Light / Dot Grid',
    figma: 'Marketing / Sections / Create Script / Background',
    layers: [
      {
        type: 'dot-field',
        id: 'dot-grid',
        figma: 'Decoration / Dot Grid / 18',
        dotPattern: {
          variant: 'grid',
          color: 'neutral',
          size: 3,
          gap: 18,
          opacity: 0.16,
          fade: 'bottom',
        },
      },
    ],
  },

  closingDarkAmbient: {
    id: 'closing-dark-ambient',
    name: 'Closing / Dark / Ambient Glow',
    figma: 'Marketing / Sections / Closing / Background',
    layers: [
      {
        type: 'gradient-blob',
        id: 'blob-primary',
        figma: 'Decoration / Blob / Primary',
        color: 'accent-5',
        colorMix: 72,
        colorStop: 68,
        size: { w: '75%', h: '85%' },
        position: { x: '50%', y: '38%', anchor: 'center' },
        blur: 'md',
        opacity: 0.62,
        motion: { preset: 'drift-a' },
      },
      {
        type: 'gradient-blob',
        id: 'blob-secondary',
        figma: 'Decoration / Blob / Secondary',
        color: 'button-primary-gradient-start',
        colorMix: 55,
        size: { w: '55%', h: '65%' },
        position: { x: '62%', y: '48%', anchor: 'center' },
        blur: 'sm',
        opacity: 0.42,
        motion: { preset: 'drift-b' },
      },
      {
        type: 'gradient-blob',
        id: 'blob-tertiary',
        figma: 'Decoration / Blob / Tertiary',
        color: 'accent-20',
        colorMix: 60,
        colorStop: 72,
        size: { w: '60%', h: '70%' },
        position: { x: '32%', y: '42%', anchor: 'center' },
        blur: 'lg',
        opacity: 0.48,
        motion: { preset: 'drift-c' },
      },
      {
        type: 'dot-field',
        id: 'dot-grid',
        figma: 'Decoration / Dot Grid / 18',
        dotPattern: {
          variant: 'grid',
          color: 'neutral',
          size: 3,
          gap: 18,
          opacity: 0.12,
          fade: 'radial',
        },
      },
      {
        type: 'linear-fade',
        id: 'fade-top',
        figma: 'Decoration / Fade / Top',
        edge: 'top',
        height: '8rem',
        from: 'accent-alt',
        fromOpacity: 0.04,
        to: 'transparent',
      },
      {
        type: 'linear-fade',
        id: 'fade-bottom',
        figma: 'Decoration / Fade / Bottom',
        edge: 'bottom',
        height: '8rem',
        from: 'accent',
        to: 'transparent',
      },
    ],
  },
} as const satisfies Record<string, DecorationScene>

export type DecorationPresetId = keyof typeof decorationPresets
